version: '3.8'

services:
  # 개발 환경
  dev:
    build:
      context: .
      target: development
    container_name: rms-dev
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    command: npm run dev

  # 프로덕션 환경
  prod:
    build:
      context: .
      target: production
    container_name: rms-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production
