// 페이지 목록 설정

export interface PageInfo {
  key: string;
  no: number;
  title: string;
  description: string;
  path: string;
  status: 'completed' | 'in-progress' | 'planned';
  screenId: string;
  message: string;
}

export const PAGES: PageInfo[] = [
  {
    key: '1',
    no: 1,
    title: 'Layout Template',
    description: '빈 템플릿 페이지',
    path: '/layout',
    status: 'completed',
    screenId: '-',
    message: '',
  },
  {
    key: '2',
    no: 2,
    title: 'Table Examples',
    description: 'Tabulator 테이블 예제',
    path: '/table-examples',
    status: 'completed',
    screenId: '-',
    message: '',
  },
  {
    key: '3',
    no: 3,
    title: 'Modals',
    description: '모달 컴포넌트',
    path: '/modal-basic',
    status: 'completed',
    screenId: '-',
    message: '',
  },
  {
    key: '4',
    no: 4,
    title: 'Dashboard',
    description: '',
    path: '/dashboard',
    status: 'completed',
    screenId: 'RMS1200',
    message: '타블레이터 레이아웃 및 푸터 테스트용 더미 데이터 포함',
  },
  {
    key: '5',
    no: 5,
    title: 'Log In',
    description: '',
    path: '/log-in',
    status: 'completed',
    screenId: 'RMS1000',
    message: '',
  },
  {
    key: '6',
    no: 6,
    title: 'Notices',
    description: '',
    path: '/notices',
    status: 'planned',
    screenId: 'RMS1300',
    message: '',
  },
  {
    key: '7',
    no: 7,
    title: 'Information',
    description: '',
    path: '/information',
    status: 'completed',
    screenId: 'RMS2100',
    message: '타블레이터 체크박스 테스트용 더미 데이터 포함',
  },
  {
    key: '8',
    no: 8,
    title: 'Groups',
    description: '',
    path: '/groups',
    status: 'completed',
    screenId: 'RMS5100',
    message: '',
  },
  {
    key: '9',
    no: 9,
    title: 'Branches',
    description: '',
    path: '/branches',
    status: 'completed',
    screenId: 'RMS5200',
    message: '',
  },
  {
    key: '10',
    no: 10,
    title: 'Models',
    description: '',
    path: '/models',
    status: 'completed',
    screenId: 'RMS5300',
    message: '',
  },
  {
    key: '11',
    no: 11,
    title: 'Error Codes',
    description: '',
    path: '/error-codes',
    status: 'completed',
    screenId: 'RMS5400',
    message: '',
  },
  {
    key: '12',
    no: 12,
    title: 'Role Management',
    description: '',
    path: '/role-management',
    status: 'completed',
    screenId: 'RMS5500',
    message: '',
  },
  {
    key: '13',
    no: 13,
    title: 'User Management',
    description: '',
    path: '/user-management',
    status: 'completed',
    screenId: 'RMS5600',
    message: '',
  },
];
